'''
Task: filter out the Wikipedia articles without any mention (without HTML tags)
Ressources: multistream_only_cui_mesh_doid.json, generated by running generate_initial_data.py
Outputs: multistream_text.json
'''

from tqdm import tqdm
import json
import time
import os

current_directory = os.getcwd().replace('code', '')
data_path = os.path.join(current_directory, 'data')
output_path = os.path.join(current_directory, 'outputs')

start_time = time.time()

with open(os.path.join(output_path, 'multistream_only_cui_mesh_doid.json'), 'r', encoding='utf-8') as jsonf:
  jsondata = json.load(jsonf)

end_time = time.time()
print(f"Loading time: {end_time - start_time:.2f} seconds")

havemention = [i for i in tqdm(jsondata) if '&lt;a href=' in i['text']]

def serialize_sets(obj):
    if isinstance(obj, set):
        return list(obj)

    return obj
    
with open(os.path.join(output_path, 'multistream_text.json'), 'w', encoding='utf-8') as jsonf:
  jsonString = json.dumps(havemention, indent=4, ensure_ascii=False, default=serialize_sets)
  jsonf.write(jsonString)