'''
Task: filter out the Wikipedia articles without CUI, MeSH ID and DOID
Ressources: multistream.json, generated by running extracted_data_to_json.py
            wiki_id_qid.csv, a mapping of Wikipedia page id and QID
            qid_cui_tui.csv, a mapping of QID, CUI, TUI and semantic type label
            qid_mesh.csv, a mapping of QID and MeSH ID
            qid_doid.csv, a mapping of QID and DOID
Outputs: multistream_only_cui_mesh_doid.json
'''

from tqdm import tqdm
import json
import pandas as pd
import time
import os

current_directory = os.getcwd().replace('code', '')
data_path = os.path.join(current_directory, 'data')
output_path = os.path.join(current_directory, 'outputs')

start_time = time.time()

with open(os.path.join(output_path, 'multistream.json'), 'r', encoding='utf-8') as jsonf:
  jsondata = json.load(jsonf)

end_time = time.time()
print(f"Loading time: {end_time - start_time:.2f} seconds")

df_qid = pd.read_csv(os.path.join(output_path, 'wiki_id_qid.csv'))
qids = list(df_qid['qid'])

df_cui = pd.read_csv(os.path.join(output_path, 'qid_cui_tui.csv'))
df_mesh = pd.read_csv(os.path.join(output_path, 'qid_mesh.csv'))
df_doid = pd.read_csv(os.path.join(output_path, 'qid_doid.csv'))

df_cui_de = df_cui[df_cui['QID'].isin(qids)].reset_index(drop=True)
df_mesh_de = df_mesh[df_mesh['QID'].isin(qids)].reset_index(drop=True)
df_doid_de = df_doid[df_doid['QID'].isin(qids)].reset_index(drop=True)

qids = list(set(list(df_mesh_de['QID']) + list(df_cui_de['QID']) + list(df_doid_de['QID'])))
wikiid_cui_mesh = df_qid[df_qid['qid'].isin(qids)]['page id'].tolist()

filtered_json = [i for i in tqdm(jsondata, ncols=80, bar_format='{l_bar}{bar}| {n_fmt}/{total_fmt}') if int(i['id']) in wikiid_cui_mesh]

def serialize_sets(obj):
    if isinstance(obj, set):
        return list(obj)

    return obj

with open(os.path.join(output_path, 'multistream_only_cui_mesh_doid.json'), 'w', encoding='utf-8') as jsonf:
  jsonString = json.dumps(filtered_json, indent=4, ensure_ascii=False, default=serialize_sets)
  jsonf.write(jsonString)